recipe: default.v1
assistant_id: MentalHealth_bot
language: en

pipeline:
- name: RegexEntityExtractor
  use_lookup_tables: True
  epochs: 100
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  entity_recognition: True
  epochs: 100
  random_seed: 42
  constrain_similarities: True
- name: FallbackClassifier
  threshold: 0.7


policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
  random_seed: 42
  constrain_similarities: True
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: True

fallbacks:
  nlu_fallback_threshold: 0.4
  core_fallback_action_name: "action_default_fallback"
  ambiguity_threshold: 0.1
